# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\"2\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0b\n\x03\x62id\x18\x03 \x01(\t\"0\n\x11\x43reateBookRequest\x12\x1b\n\x04\x62ook\x18\x01 \x01(\x0b\x32\r.library.Book\"1\n\x12\x43reateBookResponse\x12\x1b\n\x04\x62ook\x18\x01 \x01(\x0b\x32\r.library.Book\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x11UpdateBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x04\x62ook\x18\x02 \x01(\x0b\x32\r.library.Book\"\x1f\n\x11\x44\x65leteBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"1\n\x11ListBooksResponse\x12\x1c\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\r.library.Book\"\x12\n\x10ListBooksRequest2\xc9\x02\n\x0eLibraryService\x12\x44\n\nCreateBook\x12\x1a.library.CreateBookRequest\x1a\x1a.library.CreateBookRequest\x12\x31\n\x07GetBook\x12\x17.library.GetBookRequest\x1a\r.library.Book\x12\x37\n\nUpdateBook\x12\x1a.library.UpdateBookRequest\x1a\r.library.Book\x12\x41\n\nDeleteBook\x12\x1a.library.DeleteBookRequest\x1a\x17.library.DeleteResponse\x12\x42\n\tListBooks\x12\x19.library.ListBooksRequest\x1a\x1a.library.ListBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=26
  _globals['_BOOK']._serialized_end=76
  _globals['_CREATEBOOKREQUEST']._serialized_start=78
  _globals['_CREATEBOOKREQUEST']._serialized_end=126
  _globals['_CREATEBOOKRESPONSE']._serialized_start=128
  _globals['_CREATEBOOKRESPONSE']._serialized_end=177
  _globals['_GETBOOKREQUEST']._serialized_start=179
  _globals['_GETBOOKREQUEST']._serialized_end=207
  _globals['_UPDATEBOOKREQUEST']._serialized_start=209
  _globals['_UPDATEBOOKREQUEST']._serialized_end=269
  _globals['_DELETEBOOKREQUEST']._serialized_start=271
  _globals['_DELETEBOOKREQUEST']._serialized_end=302
  _globals['_DELETERESPONSE']._serialized_start=304
  _globals['_DELETERESPONSE']._serialized_end=337
  _globals['_LISTBOOKSRESPONSE']._serialized_start=339
  _globals['_LISTBOOKSRESPONSE']._serialized_end=388
  _globals['_LISTBOOKSREQUEST']._serialized_start=390
  _globals['_LISTBOOKSREQUEST']._serialized_end=408
  _globals['_LIBRARYSERVICE']._serialized_start=411
  _globals['_LIBRARYSERVICE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
